### ISSUE TITLE
DNS over https services

### ISSUE THREAD

**Issue by nshopik** [MarisKori/rknalert#2]
- cloudflare https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure/
- google https://developers.google.com/speed/public-dns/docs/dns-over-https

Можно использовать эти без каких либо серьезных ограничений

**Comment by MarisKori** [comment]
Спасибо! cloudflare не завёлся, а google работает. Скоро добавлю в расширение.

**Comment by MarisKori** [comment]
done
