### ISSUE TITLE
Firefox баг при открытии нескольких оконо браузера

### ISSUE THREAD

**Issue by IRainman** [MarisKori/rknalert#4]
Доброго времени суток!

Суть проблемы в том, что расширение (или сам браузер) некорректно обрабатывают состояние когда открыто больше чем одно окно браузера.

1. Открываем два окна браузера
2. В первом окне оставляем пустую вкладку
3. Во втором окне открываем любой сайт
4. Наблюдаем некорректное отображение информации на "Новой вкладке" в первом окне: там отображается информация о сайте во втором окне.

Возможно это не корректная обработка ситуации с активацией вкладки (перехода на вкладку) либо в расширении либо в самом браузере.

Расширение v0.18.5, Firefox 63.0.1 (32bit), Windows 7 SP1 x64

**Comment by MarisKori** [comment]
Не могу воспроизвести проблему.

На виртуальной машине установил последнюю версию Firefox (63.0.1), открыл его с нуля с пустой вкладкой, открыл новое окно, в новом окне открыл яндекс - расширение корректно показывает информацию.

**Comment by IRainman** [comment]
Почти всё кроме последнего пункта ;) Теперь переключись обратно в первое окно с пустой вкладкой и там будет информация о Яндексе вместо серой иконки и сообщения "Это вообще не сайт"

**Comment by MarisKori** [comment]
Исправлено.
