### ISSUE TITLE
"белый список ркн", но его не существует

### ISSUE THREAD

**Issue by Viktor45** [MarisKori/rknalert#6]
на некоторые сайты расширение говорит, что домен в белом списке ркн, но такого списка не существует законодательно и он нигде не опубликован, или уберите это отображение, и не вводите пользователя в заблуждение, либо найдите в действующем законодательстве где такой список существует и укажите на него, чтобы расширение не выглядело мошенническим в глазах пользователей
<img width="241" alt="2019-01-18 15 54 12" src="https://user-images.githubusercontent.com/12881238/51388038-51bdf480-1b39-11e9-99c7-908e5935991e.png">

**Comment by oripio** [comment]
@Viktor45 Нет опровержения, что его не существует.

**Comment by MarisKori** [comment]
@Viktor45,
Закона такого и правда не существует.  Но было письмо провайдерам от РКН с просьбой обеспечить бесперебойную работу важных сайтов. Да, это письмо не было публично, и у меня нет его текста. Да, в законе оно не прописано. Но оно было, так что отсутствие закона не отменяет существование списка. 

Сейчас списка и правда уже не существует у провайдеров, но у Роскомнадзора он остался, и РКН старается обеспечить работу сайтов из списка своими техническими возможностями. Таким образом, практически работа списка продолжается. То есть лучше оставить эту пометку, чтобы было видно. Если у вас есть инсайдерские сведения, которые более подробно описывают работу РКН в техническом плане, то поделитесь, пожалуйста.

Откуда я взял полный список, точно не скажу, дело было давно. Но точно помню, что гугл пришлось долго уговаривать помочь. Сейчас список, скорее всего, уже немного другой.

Спасибо за замечание. Позже поменяю некоторые формулировки в текстах расширения. Но смысла удалять метку пока не вижу.

Если какой-то сайт, по вашему мнению, в списке находится ошибочно, то интересно было бы взглянуть на него. Я не РКН, но отличить муху от котлеты смогу.

Кстати, а вы знаете, что в Китае нет запрещенных сайтов? Там нет ограничения к информации законодательно. Но при этом запрет действует. Хоть его и нет. Читай, что хочешь - если найдешь. Скачивай - если сможешь. Всё разрешено. Пользователям.
А между государством и провайдерами какие-то приватные письма, директивы, приказы, соглашения - это закон или не закон? А не всё ли равно, если оно работает и влияет на жизнь простых людей? Им в любом случае было бы интересно, как там всё устроено, пусть и не из первых рук.

**Comment by Viktor45** [comment]
Тоесть взяли самостоятельно какой то список, допустим устаревший даже неофициально(!), и решили всем сообщать что сайты в нем. При этом законодательно списка нет(!). Потом деньги за включение в этот список будете брать за включение туда сайтов рекламодателей? Как это выглядит со стороны? Вот так и выглядит.

**Comment by MarisKori** [comment]
Хм, я вас понял. Вы ищите корысть. Могу заверить, что её нет. Будете ли верить, - уже вам решать. Делалось для себя, а потом появилось желание поделиться. Сам ненавижу как рекламу, так и прочий обман во всех его проявлениях. Но если очень боитесь, то не пользуйтесь. И бог вам судья, да и мне тоже.

**Comment by dartraiden** [comment]
Достоверно известно, что Роскомнадзор периодически следит за чувствительными ресурсами на тему случайной избыточной блокировки провайдерами. При обнаружении оной провайдеру звонят из регионального отделения и просят немедленно прекратить, ну а ссориться со своим региональным филиалом РКН по пустякам (встав в позу "а на каком основании вы требуете не блокировать kremlin.ru, это моё дело") никто не собирается.

Если это не зафиксировано нигде официально, то невозможно закрыть глаза и сказать, что этого не существует.

> Да, это письмо не было публично, и у меня нет его текста.

Да не вопрос...

![rkn-whitelist-pismo](https://user-images.githubusercontent.com/5046855/52165854-22051400-2717-11e9-82dd-65e1d4c6b49f.png)

[аттач](https://storage.googleapis.com/smisc/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA%20%D1%81%D0%B5%D1%82%D0%B5%D0%B2%D1%8B%D1%85%20%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%BE%D0%B2.xlsx)

**Comment by MarisKori** [comment]
Спасибо.
Да-да, припоминаю, именно этот список ко мне и попал.

Особый конфуз был по поводу адреса `*.google.*`
Конечно же, я не стал дословно трактовать его, так что расширение не будет помечать доверенным адрес `www.google.evil.com`. Я ограничился лишь адресами `goole.com` и `google.ru` с поддоменами. 

P.S. А ещё существует **"список вечно заблокированных сайтов"**, который найти не удалось. Может быть, у вас есть такой же файл, но с "чёрным" списком?

**Comment by dartraiden** [comment]
Не слышал о таком... но, по логике, какой смысл в его существовании? Ведь заблокировано должно быть всё, что прилетает в [выгрузке](https://github.com/zapret-info/z-i). А там всё вместе: и рутрекер, который заблокирован навечно, и сайты, которые заблокированы до устранения нарушений.

**Comment by MarisKori** [comment]
@dartraiden
Смысл в том, что блокировка прилетает без суда и следствия на вновь регистрируемые зеркала, а также невозможна амнистия.
https://habr.com/ru/post/385247/

В выгрузке всё в кучу - и вечно заблокированные, и временно (до момента удаления контента).

**Comment by MarisKori** [comment]
Ах, да, самое главное.
Вечно заблокированные сайты удалены из поисковой выдачи.
Думаю, это удар ниже пояса и смысл в этом очень большой.

**Comment by dartraiden** [comment]
Удаление из вылачи это отдельный разговор. Например, Неугомонный Фил [считает](https://t.me/usher2/760), что никакого отдельного реестра, отдаваемого поисковикам, не существует.

Допустим, Google удаляет из выдачи только откровенную пиратчину, а не все сайты, заблокированные "навечно".

**Comment by dartraiden** [comment]
> В выгрузке всё в кучу

Логично, потому что выгрузка выдаётся провайдерам, а провайдеру абсолютно всё равно, заблокирован ли сайт навечно или на время, потому что, пока сайт есть в выгрузке, доступ надо блокировать.

Т.е., этот "чёрный список" нужно выцарапывать либо у поисковиков (если вообще существует у них, в чём, как я уже писал есть сомнения), либо это какой-то внутренний документ РКН. Либо искать и парсить все решения судов о бессрочной блокировке, но это малореально.

**Comment by MarisKori** [comment]
Хорошо, проверяем поисковик гугла.
Например, запросы "rutracker", "kinozal" показывают левые сайты в поисковой выдаче.
А запросы "telegram", "grani" выдают официальный сайт на первом месте.
Во всех случаях сайты занесены в реестр, только в первом случае блокировка называется "вечной", а во втором - "просто блокировка".
Такие пироги.
Так что список существует. Ну да ладно, нет так нет. Поживем, увидим, может и появится в паблике. Плюс законы сто раз перепишут.

**Comment by IRainman** [comment]
@MarisKori у Google свои тараканы на тему пиратства (DMCA и прочее), по той же причине с Yotube пропадают видео, локальный зашквар России с РосКомПозором на это вообще не влияет.
